# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: stable
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

# 指定源码分支
branches:
  only:
    - source

before_install:
  - npm install -g @angular/cli

install:
  - npm install

# 设置git提交名，邮箱;
before_script:
  - git config user.name "caifx"
  - git config user.email "747096299@qq.com"
  

# 执行构建
script:
  - ng build --prod --build-optimizer

after_success:
- cd ./a-art
- git init
- git add .
- git commit -m "Travis CI Auto Builder"
# 这里的 REPO_TOKEN 即之前在 travis 项目的环境变量里添加的
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

env:
 global:
   - GH_REF: github.com/caifx/a-art.git
